Task eleazar flores entregable v3
wizelineacademy/baz-ios-project-c1-2022 pull request #43
Opened 2022-10-03 22:09 UTC by RForce8908

Agregar los cambios para la integración final

2022-10-05 02:31 UTC, VictorUrielP requested changes

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/Billboard/MovieCell.swift
> +    func configureCellUpdate(with movie: MovieUpdate) {
Cuida los espacios
```suggestion
    }
    
    func configureCellUpdate(with movie: MovieUpdate) {
```

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/Billboard/View/BillboardViewController.swift
> +                return CGSize(width: size, height: size)
Cuida la indentación:

Xcode te puede ayudar con eso presionando `control + i`

```suggestion
        let flowayout = collectionViewLayout as? UICollectionViewFlowLayout
        let space: CGFloat = (flowayout?.minimumInteritemSpacing ?? 0.0) + (flowayout?.sectionInset.left ?? 0.0) + (flowayout?.sectionInset.right ?? 0.0)
        let size:CGFloat = (collectionView.frame.size.width - space) / 2.0
        return CGSize(width: size, height: size)
```

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/Billboard/View/BillboardViewController.swift
> +
```suggestion
    
```

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/Detail/View/DetailViewController.swift
>          }
Podríamos mover esta lógica a un modelo de datos?

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/Detail/View/DetailViewController.swift
> +        txvDetail.text = objMov?.overview ?? "No existe descripcion de la pelicula que ingresaste"
También esta lógica, podríamos moverla a un modelo de datos.

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/List/Model/Movie.swift
> +}
ResultParser no es un nombre muy descriptivo, si bien es algo genérico por el momento está ligado a resultados de películas. Un mejor nombre sería `MoviesResultParser` por ejemplo.

Cuida los espacios:

```suggestion
struct MoviesResultParser: Decodable {
    var page: Int?
    var results: [MovieUpdate]?
    var totalPages: Int?
    var totalResults: Int?
}
```

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/List/Model/Movie.swift
> +struct MovieUpdate : Decodable {
Cuida los espacios
```suggestion
struct MovieUpdate: Decodable {
```

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/Control/ParallaxView.swift
> +        }
Esta validación podría reemplazarse con un `guard`. 

Recuerda que en general preferimos el uso de `guard` sobre el `if` por permitir una mejor legibilidad en el código.

```suggestion
        guard delegateParalax != nil else { return }
        delegateParalax?.didSelectItem(iIndex: recognizer.view!.tag)
```

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/Control/ParallaxView.swift
> +        self.isUserInteractionEnabled = true
Extraigamos este código a una funciones privadas que describan lo que están haciendo, por ejemplo:

```suggestion
     addSubviews()
     setupContraints()
     setupStyles()
     addTapGestureRecognizer()
```

Las funciones podrían ser las siguientes:

```
private func addSubviews() {
        addSubview(imgDetail)
}

private func setupStyles() {
        layer.borderWidth = 0.5
        layer.backgroundColor = UIColor.white.cgColor
        layer.masksToBounds = true
        backgroundColor = .black
        imgDetail.contentMode = .scaleAspectFit
}

private func setupContraints() {
        imgDetail.topAnchor.constraint(equalTo: topAnchor).isActive = true
        imgDetail.bottomAnchor.constraint(equalTo: bottomAnchor).isActive = true
        imgDetail.leadingAnchor.constraint(equalTo: leadingAnchor).isActive = true
        imgDetail.trailingAnchor.constraint(equalTo: trailingAnchor).isActive = true
}

private func addTapGestureRecognizer() {
        addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(imageTapped)))
        isUserInteractionEnabled = true
}
```

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/Control/ParallaxView.swift
> +    var delegateParalax: ParalaxProtocol?
Revisa si es necesario agregar weak a este delegado:

```suggestion
    weak var delegateParalax: ParalaxProtocol?
```

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/Control/ParallaxView.swift
> +protocol ParalaxProtocol {
Te sugiero renombrar este protocolo de la siguiente manera:

```suggestion
protocol ParalaxViewDelegate: AnyObject {
```

Además, si lo estás usando como delegado debería extender de `AnyObject`.

Sobre la recomendación del nombre, no es recomendable utilizar el sufijo `Protocol` en los protocolos, es mejor dar un nombre genérico y las implementaciones nombrarlas con el sufijo `Imp`.

✅ Preferido:
Protocol: `Decodable`, Implementation: `DecodableMovieImp: Decodable`

🚫  No preferido:
Protocol: `DecodableProtocol`, Implementation: `DecodableModelImp: DecodableProtocol`

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/Control/ParallaxView.swift
> +    func didSelectItem(iIndex: Int)
Recuerda la [convención de nombrado de funciones en los delegates](https://github.com/raywenderlich/swift-style-guide#delegates), podrías renombrar tu método se la siguiente forma:

```suggestion
func paralaxView(_ paralaxView: ParalaxView, didSelectItem at: IndexPath)
```

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/Detail/View/DetailViewController.swift
> +extension DetailViewController : SearchProtocol {
```suggestion
}

extension DetailViewController: SearchProtocol {
```

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/Detail/View/DetailViewController.swift
> +    @objc func searchMovieCV() {
El nombre de la función no refleja claramente lo que hace, considera renombrarla, por ejemplo:
```suggestion
    @objc private func navigateToSearchMovieViewController() {
```

También considera si es necesario que esta función sea `internal`. ¿Podría ser privada?

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/Detail/View/DetailViewController.swift
> +        objMov = movie
¿Por qué es necesario settear la propiedad como `nil` y después asignarle el valor `movie`?

2022-10-05 02:31 UTC, VictorUrielP commented on BAZProjectC1/List/Model/Movie.swift
> +struct ResultParser : Decodable {
```suggestion
struct ResultParser: Decodable {
```

2022-10-05 14:55 UTC, RForce8908 commented on BAZProjectC1/Billboard/MovieCell.swift
> +    func configureCellUpdate(with movie: MovieUpdate) {
resuelto

2022-10-05 14:58 UTC, RForce8908 commented on BAZProjectC1/Billboard/View/BillboardViewController.swift
> +
borre espacios

2022-10-05 15:06 UTC, RForce8908 commented on BAZProjectC1/Control/ParallaxView.swift
> +        self.isUserInteractionEnabled = true
resuelto

2022-10-05 16:10 UTC, RForce8908 commented on BAZProjectC1/Detail/View/DetailViewController.swift
> +        objMov = movie
era para limpiar el objeto antes de hacer la asignación del nuevo valor

2022-10-05 16:20 UTC, RForce8908 commented on BAZProjectC1/Detail/View/DetailViewController.swift
> +    @objc func searchMovieCV() {
podría quedar como internal y / o privada por que solo se usa en este módulo

2022-10-17 23:52 UTC, VictorUrielP approved these changes

2022-10-17 23:53 UTC, merged