Task rocio nunez entregable2
wizelineacademy/baz-ios-project-c1-2022 pull request #49
Opened 2022-10-05 22:34 UTC by luthrocio

Se agrega el xib, el MovieCollectionViewCell y el ImageView
Se agrega la colección en la vista, se hace la carga asíncrona de las imágenes, se agrega el xib para la colección
Se agrega el archivo de constantes
Se elimina código que no se ocupa y se agrega las constantes que se ocupan en el código

2022-10-06 23:18 UTC, anaacruz approved these changes

2022-10-06 23:19 UTC, anaacruz commented
Resuelve los conflictos que hay con tu rama por favor.

2022-10-06 23:20 UTC, anaacruz requested changes
Hay conflictos por resolver

2022-10-07 01:38 UTC, luthrocio commented
Se resuelven los conflictos

2022-10-07 01:41 UTC, merged

2022-10-07 15:46 UTC, anaacruz reviewed
Cambios corregidos.