Consumo de API y modificaciones al diseño del home.
wizelineacademy/baz-ios-project-c1-2022 pull request #9
Opened 2022-09-15 18:10 UTC by Mayloa

2022-09-19 05:09 UTC, mtorres0 commented on BAZProjectC1/Home/View/HomeAppViewController.swift
> +        infoMovie = self.movies[indexPath.row]
No es necesario declarar esta variable, puedes obtener los datos directo del arreglo `movies`.

2022-09-19 05:10 UTC, mtorres0 commented on BAZProjectC1/Home/View/HomeAppViewController.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "movieCell", for: indexPath) as! MovieCell
nunca uses force unwrap. Puedes usar un guard let para obtener la celda y en caso de error retornar una celda vacía.

2022-09-19 05:11 UTC, mtorres0 commented on BAZProjectC1/Home/View/HomeAppViewController.swift
> +        super.init(nibName: "HomeAppViewController", bundle: Bundle(for: HomeAppViewController.self))
Creo que este constructor no es necesario, el bundle en toda la app es el mismo ya que no estamos usando frameworks.

2022-09-19 05:13 UTC, mtorres0 commented on BAZProjectC1/SceneDelegate.swift
> +//        guard let _ = (scene as? UIWindowScene) else { return }
Hay que evitar dejar código comentado.

2022-09-19 05:14 UTC, mtorres0 commented on BAZProjectC1/SceneDelegate.swift
> +              if let windowScene = scene as? UIWindowScene{
Hay que cuidar el identado del código. Si seleccionas este bloque de código y presionas las teclas 'ctrl + i', el identado se hace en automatico.

2022-09-19 05:17 UTC, mtorres0 commented on BAZProjectC1/Home/View/HomeAppViewController.swift
> +class HomeAppViewController: UIViewController {
Es buena práctica colocar el modificador `final` en las clases de las cuales no vas a generar subclases, es decir, que no vas a usar herencia con ellas. Comúnmente los view controller no se heredan a menos que sea un view controller con propiedades generales, que no creo que este sea el caso.

2022-09-19 05:18 UTC, mtorres0 commented on BAZProjectC1/Home/View/HomeAppViewController.swift
> +    let movieApi = MovieAPI()
MovieAPI es una dependencia del view controller. Posteriormente, usaremos inyección de dependencia para que el view controller reciba este elemento como parámetro y no se defina internamente. Eso nos ayudará cuando veamos pruebas unitarias. De momento no es necesario que lo cambies, pero sí me gustaría que vayas identificando estos temas, lo podríamos revisar en una mentoría más adelante.

2022-09-19 05:20 UTC, mtorres0 commented on BAZProjectC1/Extensions/UIImageView.swift
> +                if let image = UIImage(data: data!) {
No usar force unwrap en `data`. puedes usar un if let previo para obtener ese valor de forma segura.

2022-09-19 05:21 UTC, mtorres0 commented on BAZProjectC1/Extensions/UIImageView.swift
> +                    self.image = imgDefault
Este UIImage vacío no es necesario. La propiedad image en un UIImageView es opcional, por lo que puede ser nil sin problemas.

2022-09-19 05:21 UTC, mtorres0 commented on BAZProjectC1/Extensions/UIImageView.swift
> +                print(error!)
No usar force unwrap.

2022-09-19 05:24 UTC, mtorres0 commented on BAZProjectC1/Home/Model/Movie.swift
>      let poster_path: String
De preferencia hay que usar camelcase para el nombre de las variables/constantes. Para poderlo hacer en este caso hay que definir un enum como el siguiente. 
```
enum CodingKeys: String, CodingKey {
        case id
        case title
        case posterPath = "poster_path"
}
```

2022-09-19 05:25 UTC, mtorres0 commented on BAZProjectC1/Home/View/HomeAppViewController.swift
> +    func configureCollectionView(){
Este método debe ser privado, realmente no lo vas a usar fuera de este view controller.

2022-09-19 05:28 UTC, mtorres0 commented on BAZProjectC1/Home/ViewModel/MovieAPI.swift
> +            }catch {
Aquí no estás obteniendo el error del catch, para saber el método del fallo al decodificar. Lo que hace es imprimir el error al consumir el servicio, lo cuál no te va a dar ninguna pista al momento de que la decodificación falle.

2022-09-19 05:29 UTC, mtorres0 commented on BAZProjectC1/TrendingViewController.swift
>  class TrendingViewController: UITableViewController {
Agregar el modificador `final` antes de `class`

2022-09-19 17:17 UTC, Mayloa commented on BAZProjectC1/Home/View/HomeAppViewController.swift
> +        infoMovie = self.movies[indexPath.row]
fixed

2022-09-19 17:17 UTC, Mayloa commented on BAZProjectC1/Home/View/HomeAppViewController.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "movieCell", for: indexPath) as! MovieCell
fixed

2022-09-19 17:17 UTC, Mayloa commented on BAZProjectC1/Home/View/HomeAppViewController.swift
> +        super.init(nibName: "HomeAppViewController", bundle: Bundle(for: HomeAppViewController.self))
fixed

2022-09-19 17:18 UTC, Mayloa commented on BAZProjectC1/Home/View/HomeAppViewController.swift
> +class HomeAppViewController: UIViewController {
fixed

2022-09-19 17:18 UTC, Mayloa commented on BAZProjectC1/Extensions/UIImageView.swift
> +                if let image = UIImage(data: data!) {
fixed

2022-09-19 17:18 UTC, Mayloa commented on BAZProjectC1/Extensions/UIImageView.swift
> +                print(error!)
fixed

2022-09-19 17:18 UTC, Mayloa commented on BAZProjectC1/Home/Model/Movie.swift
>      let poster_path: String
fixed

2022-09-19 17:18 UTC, Mayloa commented on BAZProjectC1/Home/ViewModel/MovieAPI.swift
> +            }catch {
fixed

2022-09-19 17:18 UTC, Mayloa commented on BAZProjectC1/TrendingViewController.swift
>  class TrendingViewController: UITableViewController {
fixed

2022-09-19 17:19 UTC, Mayloa commented on BAZProjectC1/Home/View/HomeAppViewController.swift
> +    func configureCollectionView(){
fixed

2022-09-19 17:19 UTC, Mayloa commented on BAZProjectC1/Extensions/UIImageView.swift
> +                    self.image = imgDefault
fixed

2022-09-19 17:19 UTC, Mayloa commented on BAZProjectC1/Home/View/HomeAppViewController.swift
> +    let movieApi = MovieAPI()
fixed

2022-09-19 17:19 UTC, Mayloa commented on BAZProjectC1/SceneDelegate.swift
> +//        guard let _ = (scene as? UIWindowScene) else { return }
fixed

2022-09-19 18:01 UTC, mtorres0 requested changes

2022-09-19 18:01 UTC, mtorres0 commented on BAZProjectC1/Home/View/MovieCell/MovieCell.swift
> +
Yo creo que valdría la pena agregar el método `prepareForReuse` y reiniciar los valores de la imagen y el label.

2022-09-19 18:01 UTC, mtorres0 commented on BAZProjectC1/Home/View/MovieCell/MovieCell.swift
> +class MovieCell: UICollectionViewCell {
La clase de la celda también debe llevar `final`.

2022-09-19 18:01 UTC, mtorres0 commented on BAZProjectC1/Home/ViewModel/MovieAPI.swift
> +            }catch let error {
Pensando en la experiencia de usuario. Yo creo al caer en el catch debería haber una respuesta a la vista que notifique que ha fallado. Podrías enviar un completion con un arreglo de movies vacío y más adelante podríamos indicar con un mensaje que el servicio fallo.

2022-09-19 18:01 UTC, mtorres0 commented on BAZProjectC1/Home/ViewModel/MovieAPI.swift
> +class MovieAPI {
Agregar el modificador `final`. Todas las clases deben ser definidas así, a menos que estes segura que se va a aplicar herencia.

2022-09-19 18:01 UTC, mtorres0 commented on BAZProjectC1/Extensions/UIImageView.swift
> +        guard let url = URL(string: urlString) else { return }
Antes del return debería asignarse la imagen por defecto.

2022-09-19 18:01 UTC, mtorres0 commented on BAZProjectC1/Home/View/HomeAppViewController.swift
> +    var movies: [Movie] = []
Las variables aquí también deberían ser `private`. Siempre hay que empezar las declaraciones con la forma más restrictiva posible y sí es necesario dar acceso a otros elementos, hay que ir cambiando el modificador de acceso a como sea necesario.

2022-09-19 18:01 UTC, mtorres0 commented on BAZProjectC1/TrendingViewController.swift
>      var movies: [Movie] = []
Igual que `movies` y `movieApi` sean `private`.

2022-09-19 19:18 UTC, mtorres0 commented on BAZProjectC1/SceneDelegate.swift
> +
Hay que tratar que no haya saltos dobles de línea.

2022-09-19 22:10 UTC, Mayloa commented on BAZProjectC1/Home/View/MovieCell/MovieCell.swift
> +
fixed

2022-09-19 22:11 UTC, Mayloa commented on BAZProjectC1/Home/ViewModel/MovieAPI.swift
> +            }catch let error {
fixed

2022-09-19 22:11 UTC, Mayloa commented on BAZProjectC1/Extensions/UIImageView.swift
> +        guard let url = URL(string: urlString) else { return }
fixed

2022-09-19 22:11 UTC, Mayloa commented on BAZProjectC1/TrendingViewController.swift
>      var movies: [Movie] = []
fixed

2022-09-19 22:11 UTC, Mayloa commented on BAZProjectC1/SceneDelegate.swift
> +
fixed

2022-09-19 22:12 UTC, Mayloa commented on BAZProjectC1/Home/View/HomeAppViewController.swift
> +    var movies: [Movie] = []
fixed

2022-09-19 22:12 UTC, Mayloa commented on BAZProjectC1/Home/ViewModel/MovieAPI.swift
> +class MovieAPI {
fixed

2022-09-19 22:12 UTC, Mayloa commented on BAZProjectC1/Home/View/MovieCell/MovieCell.swift
> +class MovieCell: UICollectionViewCell {
fixed

2022-09-21 16:28 UTC, mtorres0 approved these changes

2022-09-22 16:45 UTC, merged